apiVersion: v1
kind: Service
metadata:
  name: hpp1
  namespace: opsera-hpp1-dev
  labels:
    app: hpp1
    tenant: opsera
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hpp1
