apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-last1-dev

resources:
- ../../base

labels:
- pairs:
    environment: dev
    managed-by: opsera-c2c

images:
- name: last1
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/last1

replicas:
- count: 2
  name: last1

patches:
- patch: |-
    - op: replace
      path: /spec/strategy
      value:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
  target:
    kind: Deployment
    name: last1
