apiVersion: v1
kind: Service
metadata:
  name: valentine1
  namespace: opsera-valentine1-dev
  labels:
    app: valentine1
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: valentine1
