apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-fbb3-dev
  namespace: argocd
  labels:
    app: fbb3
    tenant: opsera
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/hello-february-page.git
    targetRevision: main
    path: .opsera-fbb3/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-fbb3-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
