apiVersion: v1
kind: ServiceAccount
metadata:
  name: last1-sa
  namespace: opsera-last1-dev
  labels:
    app: last1
    tenant: opsera
    managed-by: opsera-c2c
imagePullSecrets:
  - name: ecr-registry-secret
