apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-fbb3-dev

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app: fbb3
      tenant: opsera
      managed-by: opsera-c2c
