apiVersion: v1
kind: Service
metadata:
  name: fbb3
  namespace: opsera-fbb3-dev
  labels:
    app: fbb3
    tenant: opsera
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fbb3
