apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-fbb3-dev

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev

images:
  - name: PLACEHOLDER_IMAGE
    newName: PLACEHOLDER_ECR_URI
    newTag: 35be463-20260214-165239

replicas:
  - name: fbb3
    count: 2
