apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feb14
  namespace: opsera-feb14-dev
  labels:
    app: feb14
    tenant: opsera
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - feb14-dev.agent.opsera.dev
      secretName: feb14-dev-tls
  rules:
    - host: feb14-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feb14
                port:
                  number: 80
