apiVersion: v1
kind: Service
metadata:
  name: feb14
  namespace: opsera-feb14-dev
  labels:
    app: feb14
    tenant: opsera
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: feb14
